In [1]:
import cv2
import numpy

In [2]:
img=cv2.imread("D:\\Wallpaper\\164473.jpg",1)#colour image

In [3]:
print(img)

[[[ 34  80  34]
  [ 34  80  34]
  [ 34  80  34]
  ...
  [ 50 110  49]
  [ 50 110  49]
  [ 50 110  49]]

 [[ 36  79  36]
  [ 34  79  36]
  [ 34  79  36]
  ...
  [ 50 110  49]
  [ 50 110  49]
  [ 50 110  49]]

 [[ 36  79  36]
  [ 36  79  36]
  [ 36  79  36]
  ...
  [ 50 110  49]
  [ 50 110  49]
  [ 50 110  49]]

 ...

 [[ 27  59  28]
  [ 27  59  28]
  [ 27  59  28]
  ...
  [ 27  60  26]
  [ 27  60  26]
  [ 27  60  26]]

 [[ 27  59  28]
  [ 27  59  28]
  [ 27  59  28]
  ...
  [ 27  60  26]
  [ 27  60  26]
  [ 27  60  26]]

 [[ 27  59  28]
  [ 27  59  28]
  [ 26  58  27]
  ...
  [ 27  60  26]
  [ 27  60  26]
  [ 27  60  26]]]


In [4]:
ig=cv2.imread("D:\\Wallpaper\\164473.jpg",0)#b&w image

In [5]:
print(ig)

[[61 61 61 ... 85 85 85]
 [61 61 61 ... 85 85 85]
 [61 61 61 ... 85 85 85]
 ...
 [46 46 46 ... 46 46 46]
 [46 46 46 ... 46 46 46]
 [46 46 45 ... 46 46 46]]


In [6]:
print(img.shape)#Due to colour image 3(RGB) channels

(1200, 1920, 3)


In [7]:
print(ig.shape)#Due to b&w image 1 channels

(1200, 1920)


In [8]:
print(type(img))

<class 'numpy.ndarray'>


In [9]:
cv2.imshow("Anime",img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [10]:
rs=cv2.resize(img,(600,600))
cv2.imshow("Anime",rs)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
rs2=cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))

In [12]:
cv2.imshow("Anime",rs2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
import time

In [15]:
video=cv2.VideoCapture(0)
time.sleep(3)
video.release()

In [16]:
video=cv2.VideoCapture(0)
check,frame=video.read()
print(check)
print(frame)
time.sleep(3)
video.release()

True
[[[ 15  11   6]
  [ 14   9   3]
  [ 15   9   3]
  ...
  [255 255 252]
  [255 255 252]
  [255 255 252]]

 [[ 14  10   4]
  [ 13   8   2]
  [ 15  11   3]
  ...
  [255 255 252]
  [255 255 252]
  [255 255 252]]

 [[ 14  11   4]
  [ 13  10   2]
  [ 16  13   3]
  ...
  [255 255 252]
  [255 255 252]
  [255 255 252]]

 ...

 [[ 69  57  32]
  [ 60  50  26]
  [ 60  55  30]
  ...
  [ 10  15   3]
  [ 10  13   3]
  [  9  12   3]]

 [[ 68  56  31]
  [ 64  55  29]
  [ 62  57  32]
  ...
  [ 11  14   4]
  [ 12  14   5]
  [ 11  12   5]]

 [[ 68  57  30]
  [ 67  58  32]
  [ 62  57  31]
  ...
  [ 10  13   4]
  [ 12  13   6]
  [ 13  13   7]]]


In [17]:
video=cv2.VideoCapture(0)
check,frame=video.read()
time.sleep(3)
cv2.imshow("Capturing",frame)
cv2.waitKey(0)
cv2.destroyAllWindows()
video.release()

In [18]:
video=cv2.VideoCapture(0)
a=1
while True:
    a=a+1
    check,frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Capture",gray)
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
print(a)
cv2.destroyAllWindows()
video.release()

336


In [22]:
import cv2
face_cascade=cv2.CascadeClassifier("F:\\Python\\OpenCV\\haarcascade_frontalface_default.xml")
img=cv2.imread("C:\\Users\\freak\\OneDrive\\Desktop\\screenshot\\2.jpg")
gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
faces=face_cascade.detectMultiScale(gray,1.1,4)
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
import cv2
face_cascade = cv2.CascadeClassifier('F:\\Python\\OpenCV\\haarcascade_frontalface_default.xml')
cap = cv2.VideoCapture(0)

while True:
    _, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)

    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

    cv2.imshow('img', img)

    k = cv2.waitKey(1)
    if k== ord('q'):
        break
cap.release()
cv2.destroyAllWindows()